const express = require('express');
const router = express.Router();
const multer = require('multer');
const jwt = require('jsonwebtoken');
const { google } = require('googleapis');
const QRCode = require('qrcode');
const { createWorker } = require('tesseract.js');
const db = require('../config/db');

// --- 1. DOM POLYFILLS FOR PDF-PARSE ON NODE 22/24 ---
if (typeof globalThis.DOMMatrix === 'undefined') {
  globalThis.DOMMatrix = class DOMMatrix {};
}
if (typeof globalThis.ImageData === 'undefined') {
  globalThis.ImageData = class ImageData {};
}
if (typeof globalThis.Path2D === 'undefined') {
  globalThis.Path2D = class Path2D {};
}

// --- 2. MULTI-PATH PDF-PARSE RESOLVER ---
let pdfParse = null;
try {
  const loadedPdf = require('pdf-parse');
  if (typeof loadedPdf === 'function') {
    pdfParse = loadedPdf;
  } else if (loadedPdf && typeof loadedPdf.default === 'function') {
    pdfParse = loadedPdf.default;
  } else {
    pdfParse = require('pdf-parse/lib/pdf-parse.js');
  }
} catch (err) {
  try {
    pdfParse = require('pdf-parse/lib/pdf-parse.js');
  } catch (subErr) {
    console.warn('⚠️ Notice: pdf-parse direct core file load attempted:', subErr.message);
  }
}

// Imports ALL original controller functions
const { 
  getPermitStats, 
  getMonthlyStats, 
  getPermits, 
  archivePermit, 
  deletePermit, 
  updatePermit, 
  removePermitFile 
} = require('../controllers/permitController');

const storage = multer.memoryStorage();
const upload = multer({ storage: storage });

const archivalUploads = upload.fields([
  { name: 'certificate', maxCount: 1 }, 
  { name: 'drawings', maxCount: 100 },
  { name: 'permitForm', maxCount: 20 },
  { name: 'receipts', maxCount: 10 }
]);

// Helper function to extract regex matches safely from OCR text
const extractPattern = (text, regex) => {
  const match = text.match(regex);
  return match && match[1] ? match[1].trim() : '';
};

// --- GOOGLE OAUTH 2.0 USER AUTHENTICATION HELPER ---
const getGoogleDriveClient = () => {
  const clientId = process.env.GOOGLE_CLIENT_ID;
  const clientSecret = process.env.GOOGLE_CLIENT_SECRET;
  const refreshToken = process.env.GOOGLE_REFRESH_TOKEN;

  if (!clientId || !clientSecret || !refreshToken) {
    throw new Error('Missing Google OAuth environment variables (CLIENT_ID, CLIENT_SECRET, or REFRESH_TOKEN) on Render.');
  }

  const oauth2Client = new google.auth.OAuth2(
    clientId,
    clientSecret,
    process.env.GOOGLE_REDIRECT_URI || 'https://developers.google.com/oauthplayground'
  );

  oauth2Client.setCredentials({ refresh_token: refreshToken });
  return { oauth2Client, drive: google.drive({ version: 'v3', auth: oauth2Client }) };
};

// --- ENSURE SUPABASE PERMITS TABLE & AUTO-FIX STATUS ---
const ensureTablesExist = async () => {
  try {
    await db.query(`
      CREATE TABLE IF NOT EXISTS permits (
        id bigint generated by default as identity not null,
        created_at timestamp with time zone not null default timezone ('utc'::text, now()),
        permit_number text not null,
        date_issued text not null,
        purpose text not null,
        applicant_name text not null,
        phone text null,
        address text not null,
        location text not null,
        certificate_link text null,
        drawings_links text null,
        permit_form_link text null,
        receipts_links text null,
        upload_status text null default 'completed'::text,
        status character varying(50) null default 'Synced'::character varying,
        constraint permits_pkey primary key (id)
      );
    `);

    await db.query(`ALTER TABLE permits ADD COLUMN IF NOT EXISTS upload_status text DEFAULT 'completed';`);
    await db.query(`ALTER TABLE permits ADD COLUMN IF NOT EXISTS status VARCHAR(50) DEFAULT 'Synced';`);

    await db.query(`
      UPDATE permits 
      SET status = 'Synced', upload_status = 'completed' 
      WHERE status IS NULL OR LOWER(status) = 'processing' OR LOWER(upload_status) = 'pending';
    `);

  } catch (err) {
    console.error("Error verifying Supabase permits table structure:", err);
  }
};

// --- JWT OFFICER AUTHENTICATION MIDDLEWARE ---
const requireAuth = (req, res, next) => {
  const authHeader = req.headers['authorization'];

  if (authHeader && authHeader.startsWith('Bearer ')) {
    const token = authHeader.split(' ')[1];
    try {
      const decoded = jwt.verify(token, process.env.JWT_SECRET || 'nipda_secret_key_2026');
      req.user = decoded;
      return next();
    } catch (err) {
      return res.status(401).json({ 
        success: false, 
        message: "Unauthorized: Invalid or expired session token. Please log in again." 
      });
    }
  }

  return res.status(401).json({ 
    success: false, 
    message: "Unauthorized: Officer session token required." 
  });
};

// ==========================================
// 0. SERVER HEALTH CHECK ENDPOINT
// ==========================================
router.get('/health', (req, res) => {
  res.status(200).json({
    status: 'UP',
    message: 'NIPDA BPMS Backend is active and healthy',
    timestamp: new Date().toISOString(),
    uptime: process.uptime()
  });
});

// ==========================================
// 1. DYNAMIC SUBFOLDER CREATOR
// ==========================================
router.post('/create-permit-folders', requireAuth, async (req, res) => {
  try {
    const { permitNumber, applicantName, categories } = req.body;
    const rootFolderId = process.env.GOOGLE_DRIVE_FOLDER_ID;

    if (!rootFolderId) {
      return res.status(500).json({ 
        success: false, 
        message: 'Server Configuration Error: GOOGLE_DRIVE_FOLDER_ID missing on Render.' 
      });
    }

    const { drive } = getGoogleDriveClient();

    const getOrCreateFolder = async (folderName, parentId) => {
      const escapedName = folderName.replace(/\\/g, '\\\\').replace(/'/g, "\\'");
      const q = `mimeType='application/vnd.google-apps.folder' and name='${escapedName}' and '${parentId}' in parents and trashed=false`;
      
      try {
        const searchRes = await drive.files.list({
          q: q,
          fields: 'files(id, name)',
          spaces: 'drive',
          pageSize: 10
        });

        if (searchRes.data.files && searchRes.data.files.length > 0) {
          return searchRes.data.files[0].id;
        }
      } catch (searchErr) {
        console.error("Folder search query warning:", searchErr.message);
      }

      const createRes = await drive.files.create({
        requestBody: {
          name: folderName,
          mimeType: 'application/vnd.google-apps.folder',
          parents: [parentId]
        },
        fields: 'id'
      });

      return createRes.data.id;
    };

    const cleanPermitNum = (permitNumber || '').replace(/[\/\\]/g, '_').trim();
    const cleanApplicant = (applicantName || '').replace(/[\/\\]/g, '-').trim();

    const masterFolderName = cleanApplicant 
      ? `${cleanPermitNum} - ${cleanApplicant}` 
      : cleanPermitNum;

    const masterFolderId = await getOrCreateFolder(masterFolderName, rootFolderId);

    try {
      await drive.permissions.create({
        fileId: masterFolderId,
        requestBody: {
          role: 'reader',
          type: 'anyone'
        }
      });
    } catch (permErr) {
      console.warn("Notice: Master folder permission setting skipped or already public:", permErr.message);
    }

    const categoryMap = {
      certificate: '1. Permit Certificates',
      drawings: '2. Architectural Drawings',
      permitForm: '3. Permit Forms',
      receipts: '4. Receipts & Bills'
    };

    const subfolders = {};
    const requestedCategories = Array.isArray(categories) && categories.length > 0 
      ? categories 
      : Object.keys(categoryMap);

    for (const cat of requestedCategories) {
      if (categoryMap[cat]) {
        subfolders[cat] = await getOrCreateFolder(categoryMap[cat], masterFolderId);
      }
    }

    res.json({
      success: true,
      masterFolderId,
      subfolders
    });

  } catch (err) {
    console.error("Folder structure creation error:", err);
    res.status(500).json({ success: false, message: `Folder Creation Error: ${err.message}` });
  }
});

// ==========================================
// 2. DIRECT DRIVE UPLOAD SESSION ROUTE
// ==========================================
router.post('/get-drive-upload-url', requireAuth, async (req, res) => {
  try {
    const { targetFolderId, fileName, mimeType, fileSize } = req.body;

    if (!targetFolderId) {
      return res.status(400).json({ 
        success: false, 
        message: 'Missing target subfolder ID.' 
      });
    }

    const { oauth2Client } = getGoogleDriveClient();
    const tokenResponse = await oauth2Client.getAccessToken();
    const accessToken = typeof tokenResponse === 'string' ? tokenResponse : tokenResponse?.token;

    const clientOrigin = req.headers.origin || req.headers.referer || '*';

    const googleRes = await fetch('https://www.googleapis.com/upload/drive/v3/files?uploadType=resumable', {
      method: 'POST',
      headers: {
        'Authorization': `Bearer ${accessToken}`,
        'Content-Type': 'application/json',
        'X-Upload-Content-Type': mimeType || 'application/pdf',
        'X-Upload-Content-Length': fileSize ? String(fileSize) : undefined,
        'Origin': clientOrigin
      },
      body: JSON.stringify({
        name: `${Date.now()}-${fileName}`,
        parents: [targetFolderId]
      })
    });

    const uploadUrl = googleRes.headers.get('location');

    if (!uploadUrl) {
      const errText = await googleRes.text();
      console.error('Google Drive session creation failed:', errText);
      return res.status(500).json({ 
        success: false, 
        message: 'Google Drive rejected upload session creation.' 
      });
    }

    res.json({ success: true, uploadUrl });
  } catch (err) {
    console.error('Error generating Google Drive upload URL:', err);
    res.status(500).json({ 
      success: false, 
      message: `Google Drive Session Error: ${err.message}` 
    });
  }
});

// ==========================================
// 3. METADATA SAVER ROUTE
// ==========================================
router.post('/archive-metadata', requireAuth, async (req, res) => {
  try {
    await ensureTablesExist();

    const { 
      permitNumber, dateIssued, purpose, applicantName, 
      phone, address, location, certificateLink, 
      drawingsLinks, permitFormLink, receiptsLinks 
    } = req.body;

    const query = `
      INSERT INTO permits 
      (permit_number, date_issued, purpose, applicant_name, phone, address, location, certificate_link, drawings_links, permit_form_link, receipts_links, upload_status, status)
      VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, 'completed', 'Synced')
      RETURNING *;
    `;
    
    const values = [
      permitNumber, 
      dateIssued, 
      purpose, 
      applicantName, 
      phone || null, 
      address, 
      location, 
      certificateLink || null, 
      drawingsLinks || null, 
      permitFormLink || null, 
      receiptsLinks || null
    ];

    const dbResponse = await db.query(query, values);
    const rows = Array.isArray(dbResponse) ? dbResponse : (dbResponse && dbResponse.rows ? dbResponse.rows : []);
    const savedRecord = rows.length > 0 ? rows[0] : null;

    res.json({ success: true, data: savedRecord });
  } catch (err) {
    console.error("Database metadata insert error:", err);
    res.status(500).json({ 
      success: false, 
      message: `Database Insert Error: ${err.message}` 
    });
  }
});

// ==========================================
// 4. PRINTABLE QR CODE GENERATOR ROUTE
// ==========================================
const handleQrGeneration = async (req, res) => {
  try {
    const permitNum = req.query.id || req.query.permitNumber || req.params.permitNumber;

    if (!permitNum) {
      return res.status(400).json({ success: false, message: 'Missing permit number for QR generation.' });
    }
    
    const clientBaseUrl = process.env.CLIENT_URL || req.headers.origin || 'https://nipma-bpms.vercel.app';
    const verificationUrl = `${clientBaseUrl.replace(/\/$/, '')}/verify-permit?id=${encodeURIComponent(permitNum)}`;

    const qrImageBase64 = await QRCode.toDataURL(verificationUrl, {
      errorCorrectionLevel: 'H',
      width: 300,
      margin: 2,
      color: {
        dark: '#0f172a',
        light: '#ffffff'
      }
    });

    res.json({ 
      success: true, 
      permitNumber: permitNum, 
      qrCode: qrImageBase64,
      verificationUrl: verificationUrl 
    });
  } catch (err) {
    console.error('QR Code Generation Error:', err);
    res.status(500).json({ success: false, message: 'Failed to generate QR code' });
  }
};

router.get('/qr', handleQrGeneration);
router.get('/qr/:permitNumber', handleQrGeneration);

// ==========================================
// 5. OCR & PDF DOCUMENT TEXT EXTRACTION ROUTE
// ==========================================
router.post('/extract-ocr', requireAuth, upload.single('document'), async (req, res) => {
  let worker = null;
  try {
    if (!req.file) {
      return res.status(400).json({ success: false, message: 'No document file uploaded for text extraction.' });
    }

    const mimeType = req.file.mimetype || '';
    const originalName = (req.file.originalname || '').toLowerCase();
    const isPdf = mimeType === 'application/pdf' || originalName.endsWith('.pdf');

    let extractedText = '';

    if (isPdf) {
      if (typeof pdfParse !== 'function') {
        return res.status(500).json({
          success: false,
          message: 'PDF parser component failed to load on the server. Please upload a PNG or JPG image instead.'
        });
      }

      try {
        const pdfData = await pdfParse(req.file.buffer);
        extractedText = (pdfData && pdfData.text) ? pdfData.text.trim() : '';

        if (!extractedText) {
          return res.status(400).json({
            success: false,
            message: 'No text layer found in this PDF. If this is a scanned photo inside a PDF, please upload it as a PNG or JPG image.'
          });
        }
      } catch (pdfErr) {
        console.error('PDF Extraction Error:', pdfErr.message);
        return res.status(400).json({
          success: false,
          message: 'Failed to read PDF. Please ensure the file is unencrypted and readable.'
        });
      }
    } else {
      worker = await createWorker('eng');
      const { data } = await worker.recognize(req.file.buffer);
      extractedText = data.text || '';
    }

    const extractedData = {
      permitNumber: extractPattern(extractedText, /(?:Permit|Cert|Licence)\s*(?:No|Number|#)?[\s:]*([A-Za-z0-9_\-\/]+)/i),
      applicantName: extractPattern(extractedText, /(?:Applicant|Issued To|Name)[\s:]*([A-Za-z\s]{3,30})/i),
      dateIssued: extractPattern(extractedText, /(?:Date|Issued)[\s:]*(\d{1,2}[\/\.-]\d{1,2}[\/\.-]\d{2,4})/i),
      purpose: extractPattern(extractedText, /(?:Purpose|Development|Type)[\s:]*([A-Za-z0-9\s]{3,40})/i),
      address: extractPattern(extractedText, /(?:Address|Location|Site)[\s:]*([A-Za-z0-9\s,.-]{3,50})/i),
      rawText: extractedText
    };

    res.json({
      success: true,
      data: extractedData
    });

  } catch (err) {
    console.error('Text Extraction Error:', err);
    res.status(500).json({ success: false, message: `Text Extraction Error: ${err.message}` });
  } finally {
    if (worker) {
      await worker.terminate();
    }
  }
});

// ==========================================
// 6. PUBLIC PERMIT VERIFICATION ROUTE
// ==========================================
const handlePermitVerification = async (req, res) => {
  res.setHeader('Access-Control-Allow-Origin', '*');
  res.setHeader('Access-Control-Allow-Methods', 'GET, OPTIONS');

  try {
    const rawPermitNum = req.query.permitNumber || req.query.id || req.params.permitNumber;

    if (!rawPermitNum) {
      return res.status(400).json({ success: false, message: 'Missing permit number parameter.' });
    }

    const permitNum = decodeURIComponent(rawPermitNum).trim();
    console.log(`🔍 [VERIFY REQUEST] Searching for permit number: "${permitNum}"`);

    const query = `
      SELECT * 
      FROM permits 
      WHERE (
        LOWER(TRIM(permit_number)) = LOWER(TRIM($1))
        OR REGEXP_REPLACE(LOWER(permit_number), '[^a-z0-9]', '', 'g') = REGEXP_REPLACE(LOWER($1), '[^a-z0-9]', '', 'g')
      )
      AND permit_number IS NOT NULL 
      AND TRIM(permit_number) != ''
      ORDER BY id DESC 
      LIMIT 1;
    `;
    
    const dbResponse = await db.query(query, [permitNum]);
    let rows = Array.isArray(dbResponse) ? dbResponse : (dbResponse && dbResponse.rows ? dbResponse.rows : []);
    
    if (rows.length === 0) {
      console.warn(`⚠️ [VERIFY FAILED] No DB match found for permit number: "${permitNum}"`);
      return res.status(404).json({ 
        success: false, 
        message: `Permit "${permitNum}" not found in official archives.` 
      });
    }

    let record = rows[0];
    while (Array.isArray(record) && record.length > 0) {
      record = record[0];
    }

    console.log("✅ [VERIFY SUCCESS] Unwrapped Record Object:", record);

    const permit_number = record.permit_number || record.permitNumber || permitNum;
    const applicant_name = record.applicant_name || record.applicantName || 'N/A';
    const date_issued = record.date_issued || record.dateIssued || record.created_at || 'N/A';
    const purpose = record.purpose || 'RESIDENTIAL';
    const location = record.location || 'N/A';
    const address = record.address || 'N/A';
    const phone = record.phone || 'N/A';

    const formattedData = {
      permit_number,
      permitNumber: permit_number,
      applicant_name: String(applicant_name).toUpperCase(),
      applicantName: String(applicant_name).toUpperCase(),
      date_issued: String(date_issued),
      dateIssued: String(date_issued),
      purpose: String(purpose).toUpperCase(),
      location: String(location).toUpperCase(),
      address: String(address).toUpperCase(),
      phone: String(phone),
      status: record.status || 'Synced'
    };

    res.json({ success: true, data: formattedData });

  } catch (err) {
    console.error("❌ Verification Database Error:", err);
    res.status(500).json({ success: false, message: 'Server error during permit verification.' });
  }
};

router.get('/verify-record', handlePermitVerification);
router.get('/verify', handlePermitVerification);
router.get('/verify/:permitNumber', handlePermitVerification);

// ==========================================
// 7. CONTROLLER ROUTES
// ==========================================
router.get('/stats', getPermitStats);
router.get('/monthly-stats', getMonthlyStats); 
router.get('/', getPermits);

router.post('/archive', requireAuth, archivalUploads, archivePermit);
router.delete('/:id', requireAuth, deletePermit);
router.put('/:id', requireAuth, updatePermit);
router.put('/:id/remove-file', requireAuth, removePermitFile);

// ==========================================
// EXPORT ROUTER
// ==========================================
module.exports = router;