const express = require('express');
const router = express.Router();
const multer = require('multer');
const jwt = require('jsonwebtoken');
const { google } = require('googleapis');
const db = require('../config/db');

// Imports ALL 7 original controller functions
const { 
  getPermitStats, 
  getMonthlyStats, 
  getPermits, 
  archivePermit, 
  deletePermit, 
  updatePermit, 
  removePermitFile 
} = require('../controllers/permitController');

const storage = multer.memoryStorage();
const upload = multer({ storage: storage });

const archivalUploads = upload.fields([
  { name: 'certificate', maxCount: 1 }, 
  { name: 'drawings', maxCount: 100 },
  { name: 'permitForm', maxCount: 20 },
  { name: 'receipts', maxCount: 10 }
]);

// --- ENSURE SUPABASE PERMITS TABLE & AUTO-FIX STATUS ---
const ensureTablesExist = async () => {
  try {
    await db.query(`
      CREATE TABLE IF NOT EXISTS permits (
        id bigint generated by default as identity not null,
        created_at timestamp with time zone not null default timezone ('utc'::text, now()),
        permit_number text not null,
        date_issued text not null,
        purpose text not null,
        applicant_name text not null,
        phone text null,
        address text not null,
        location text not null,
        certificate_link text null,
        drawings_links text null,
        permit_form_link text null,
        receipts_links text null,
        upload_status text null default 'completed'::text,
        status character varying(50) null default 'Synced'::character varying,
        constraint permits_pkey primary key (id)
      );
    `);

    await db.query(`ALTER TABLE permits ADD COLUMN IF NOT EXISTS upload_status text DEFAULT 'completed';`);
    await db.query(`ALTER TABLE permits ADD COLUMN IF NOT EXISTS status VARCHAR(50) DEFAULT 'Synced';`);

    // Convert any legacy pending/processing records to Synced
    await db.query(`
      UPDATE permits 
      SET status = 'Synced', upload_status = 'completed' 
      WHERE status IS NULL OR LOWER(status) = 'processing' OR LOWER(upload_status) = 'pending';
    `);

  } catch (err) {
    console.error("Error verifying Supabase permits table structure:", err);
  }
};

// --- JWT OFFICER AUTHENTICATION MIDDLEWARE ---
const requireAuth = (req, res, next) => {
  const authHeader = req.headers['authorization'];

  if (authHeader && authHeader.startsWith('Bearer ')) {
    const token = authHeader.split(' ')[1];
    try {
      const decoded = jwt.verify(token, process.env.JWT_SECRET || 'nipda_secret_key_2026');
      req.user = decoded;
      return next();
    } catch (err) {
      return res.status(401).json({ 
        success: false, 
        message: "Unauthorized: Invalid or expired session token. Please log in again." 
      });
    }
  }

  return res.status(401).json({ 
    success: false, 
    message: "Unauthorized: Officer session token required." 
  });
};

// ==========================================
// 1. SINGLE MASTER FOLDER & SUBFOLDERS CREATOR (WITH ESCAPED SEARCH)
// ==========================================
router.post('/create-permit-folders', requireAuth, async (req, res) => {
  try {
    const { permitNumber, applicantName } = req.body;

    const clientId = process.env.GOOGLE_CLIENT_ID;
    const clientSecret = process.env.GOOGLE_CLIENT_SECRET;
    const refreshToken = process.env.GOOGLE_REFRESH_TOKEN;
    const rootFolderId = process.env.GOOGLE_DRIVE_FOLDER_ID;

    if (!clientId || !clientSecret || !refreshToken || !rootFolderId) {
      return res.status(500).json({ 
        success: false, 
        message: 'Server Configuration Error: Google OAuth keys missing on Render.' 
      });
    }

    const oauth2Client = new google.auth.OAuth2(
      clientId,
      clientSecret,
      process.env.GOOGLE_REDIRECT_URI || 'https://developers.google.com/oauthplayground'
    );

    oauth2Client.setCredentials({ refresh_token: refreshToken });
    const drive = google.drive({ version: 'v3', auth: oauth2Client });

    // Helper: Find or create Google Drive Folder with strict quote escaping
    const getOrCreateFolder = async (folderName, parentId) => {
      const escapedName = folderName.replace(/\\/g, '\\\\').replace(/'/g, "\\'");
      const q = `mimeType='application/vnd.google-apps.folder' and name='${escapedName}' and '${parentId}' in parents and trashed=false`;
      
      try {
        const searchRes = await drive.files.list({
          q: q,
          fields: 'files(id, name)',
          spaces: 'drive',
          pageSize: 10
        });

        if (searchRes.data.files && searchRes.data.files.length > 0) {
          // Folder already exists! Return its ID
          return searchRes.data.files[0].id;
        }
      } catch (searchErr) {
        console.error("Folder search query warning:", searchErr.message);
      }

      // Create new folder if not found
      const createRes = await drive.files.create({
        requestBody: {
          name: folderName,
          mimeType: 'application/vnd.google-apps.folder',
          parents: [parentId]
        },
        fields: 'id'
      });

      return createRes.data.id;
    };

    // Format single master folder name: NIPDA_TSOP_26_02 - Applicant Name
    const cleanPermitNum = (permitNumber || '').replace(/[\/\\]/g, '_').trim();
    const cleanApplicant = (applicantName || '').replace(/[\/\\]/g, '-').trim();

    const masterFolderName = cleanApplicant 
      ? `${cleanPermitNum} - ${cleanApplicant}` 
      : cleanPermitNum;

    // A. Create/Fetch Exactly ONE Master Permit Folder
    const masterFolderId = await getOrCreateFolder(masterFolderName, rootFolderId);

    // B. Create/Fetch All 4 Subfolders Inside the Master Folder
    const certFolderId = await getOrCreateFolder('1. Permit Certificates', masterFolderId);
    const drawingsFolderId = await getOrCreateFolder('2. Architectural Drawings', masterFolderId);
    const formFolderId = await getOrCreateFolder('3. Permit Forms', masterFolderId);
    const receiptsFolderId = await getOrCreateFolder('4. Receipts & Bills', masterFolderId);

    res.json({
      success: true,
      masterFolderId,
      subfolders: {
        certificate: certFolderId,
        drawings: drawingsFolderId,
        permitForm: formFolderId,
        receipts: receiptsFolderId
      }
    });

  } catch (err) {
    console.error("Folder structure creation error:", err);
    res.status(500).json({ success: false, message: `Folder Creation Error: ${err.message}` });
  }
});

// ==========================================
// 2. DIRECT DRIVE UPLOAD SESSION ROUTE
// ==========================================
router.post('/get-drive-upload-url', requireAuth, async (req, res) => {
  try {
    const { targetFolderId, fileName, mimeType, fileSize } = req.body;

    const clientId = process.env.GOOGLE_CLIENT_ID;
    const clientSecret = process.env.GOOGLE_CLIENT_SECRET;
    const refreshToken = process.env.GOOGLE_REFRESH_TOKEN;

    if (!clientId || !clientSecret || !refreshToken || !targetFolderId) {
      return res.status(500).json({ 
        success: false, 
        message: 'Missing target subfolder ID or Google OAuth keys.' 
      });
    }

    const oauth2Client = new google.auth.OAuth2(
      clientId,
      clientSecret,
      process.env.GOOGLE_REDIRECT_URI || 'https://developers.google.com/oauthplayground'
    );

    oauth2Client.setCredentials({ refresh_token: refreshToken });

    const tokenResponse = await oauth2Client.getAccessToken();
    const accessToken = typeof tokenResponse === 'string' ? tokenResponse : tokenResponse?.token;

    const clientOrigin = req.headers.origin || req.headers.referer || '*';

    const googleRes = await fetch('https://www.googleapis.com/upload/drive/v3/files?uploadType=resumable', {
      method: 'POST',
      headers: {
        'Authorization': `Bearer ${accessToken}`,
        'Content-Type': 'application/json',
        'X-Upload-Content-Type': mimeType || 'application/pdf',
        'X-Upload-Content-Length': fileSize ? String(fileSize) : undefined,
        'Origin': clientOrigin
      },
      body: JSON.stringify({
        name: `${Date.now()}-${fileName}`,
        parents: [targetFolderId]
      })
    });

    const uploadUrl = googleRes.headers.get('location');

    if (!uploadUrl) {
      const errText = await googleRes.text();
      console.error('Google Drive session creation failed:', errText);
      return res.status(500).json({ 
        success: false, 
        message: 'Google Drive rejected upload session creation.' 
      });
    }

    res.json({ success: true, uploadUrl });
  } catch (err) {
    console.error('Error generating Google Drive upload URL:', err);
    res.status(500).json({ 
      success: false, 
      message: `Google Drive Session Error: ${err.message}` 
    });
  }
});

// ==========================================
// 3. METADATA SAVER ROUTE (SUPABASE PERMITS TABLE ONLY)
// ==========================================
router.post('/archive-metadata', requireAuth, async (req, res) => {
  try {
    await ensureTablesExist();

    const { 
      permitNumber, dateIssued, purpose, applicantName, 
      phone, address, location, certificateLink, 
      drawingsLinks, permitFormLink, receiptsLinks 
    } = req.body;

    const query = `
      INSERT INTO permits 
      (permit_number, date_issued, purpose, applicant_name, phone, address, location, certificate_link, drawings_links, permit_form_link, receipts_links, upload_status, status)
      VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, 'completed', 'Synced')
      RETURNING *;
    `;
    
    const values = [
      permitNumber, 
      dateIssued, 
      purpose, 
      applicantName, 
      phone || null, 
      address, 
      location, 
      certificateLink || null, 
      drawingsLinks || null, 
      permitFormLink || null, 
      receiptsLinks || null
    ];

    const dbResponse = await db.query(query, values);
    const rows = Array.isArray(dbResponse) ? dbResponse : (dbResponse && dbResponse.rows ? dbResponse.rows : []);
    const savedRecord = rows.length > 0 ? rows[0] : null;

    res.json({ success: true, data: savedRecord });
  } catch (err) {
    console.error("Database metadata insert error:", err);
    res.status(500).json({ 
      success: false, 
      message: `Database Insert Error: ${err.message}` 
    });
  }
});

// ==========================================
// PUBLIC ROUTES
// ==========================================
router.get('/stats', getPermitStats);
router.get('/monthly-stats', getMonthlyStats); 
router.get('/', getPermits);

// ==========================================
// PROTECTED ROUTES
// ==========================================
router.post('/archive', requireAuth, archivalUploads, archivePermit);
router.delete('/:id', requireAuth, deletePermit);
router.put('/:id', requireAuth, updatePermit);
router.put('/:id/remove-file', requireAuth, removePermitFile);

module.exports = router;